### ISSUE TITLE
Use of `process.emitWarning` causes noise for consumers

### ISSUE THREAD

**Issue by bakkot** [esfx/esfx#28]
ecmarkup consumes this projects for CancellationToken. Right now building any project with ecmarkup will print `Deprecation: Use 'new Disposable(dispose)' instead.` to standard error, which is not a particularly helpful error given that neither the consumer nor ecmarkup invokes `Disposable` at all.

It seems like using `process.emitWarning` is adding noise to all transitive consumers of a library using a deprecated API - that seems bad. I'm not sure what transitive consumers of this library are intended to do about the message except open an issue on the upstream repository, so that's what I'm doing.

**Comment by bakkot** [comment]
From `--trace-warnings` I can see the immediate problem is [this line of code](https://github.com/esfx/esfx/blob/b301252051989623db0e92fb6c6136133d8706f1/packages/cancelable/src/index.ts#L22), which is using the deprecated API, but the larger problem is that using `proces.emitWarning` for deprecation adds noise to downstream consumers who may have no direct use of this library.

**Comment by rbuckton** [comment]
I'll post an update that addresses this tonight. I've been iterating on the design while testing out an API change I proposed in https://github/tc39/proposal-explicit-resource-management.

**Comment by rbuckton** [comment]
I've published an update to the various packages that directly depend on `@esfx/disposable` to remove the warning. Please let me know if you're still seeing this after updating.

**Comment by bakkot** [comment]
> Please let me know if you're still seeing this after updating.

Seems to be gone, thanks.
