### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by unicomp21** [esfx/esfx#57]
Compiled with problems:X

ERROR in ./node_modules/@esfx/collections-hashmap/dist/esm/index.js 181:8

Module parse failed: 'import' and 'export' may only appear at the top level (181:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|             return getPrime(newSize);
|         }
>         export function createHashEntry() {
|             return {
|                 prevEntry: undefined,

ERROR in ./node_modules/@esfx/collections-hashset/dist/esm/index.js 211:8

Module parse failed: 'import' and 'export' may only appear at the top level (211:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|             return getPrime(newSize);
|         }
>         export function createHashEntry() {
|             return {
|                 prevEntry: undefined,

ERROR in ./node_modules/@esfx/collections-sortedmap/dist/esm/index.js 36:8

Module parse failed: 'import' and 'export' may only appear at the top level (36:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|            limitations under the License.
|         */
>         export function binarySearch(array, key, comparer) {
|             if (array.length === 0)
|                 return -1;

ERROR in ./node_modules/@esfx/collections-sortedset/dist/esm/index.js 38:8

Module parse failed: 'import' and 'export' may only appear at the top level (38:8)
File was processed with these loaders:
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|            limitations under the License.
|         */
>         export function binarySearch(array, key, comparer) {
|             if (array.length === 0)
|                 return -1;

ERROR in ./node_modules/@esfx/equatable/dist/esm/index.js 18:0-40

Module not found: Error: Can't resolve '#hashCode' in '/Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm'

**Comment by rbuckton** [comment]
The issues with `export` are also mentioned in #56, and are fixed in 885cd2206f824d1c792f3188e91a2963ed5b6d26. I'll publish a new version as soon as I have finished putting together a publish workflow that can build the linux and macos native binaries needed by `@esfx/equatable`.

I'll need to look into the issue with `#hashCode` though.

**Comment by unicomp21** [comment]
using latest from a few hours ago:

ERROR in ./node_modules/@esfx/equatable/dist/esm/index.js 18:0-40
Module not found: Error: Can't resolve '#hashCode' in '/Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm'
resolve '#hashCode' in '/Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm'
  using description file: /Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
 @ ./src/voxels/point.ts 1:0-68 9:5-21 15:5-19 17:13-26 17:31-38 18:13-26 18:31-38 19:13-26 19:31-38
 @ ./src/voxels/voxels_cube.ts 3:0-33 20:15-33
 @ ./src/voxels/scratchpad.ts 1:0-44 11:27-38
 @ ./src/index.ts 15:0-49 52:42-63

webpack 5.74.0 compiled with 1 error in 18731 ms

**Comment by rbuckton** [comment]
Thanks! I'll look at this more this afternoon.

**Comment by rbuckton** [comment]
> Field 'browser' doesn't contain a valid alias configuration

I take it webpack is looking for a `"browser"` entrypoint in package.json? Odd that it requires that for `"imports"` entries but not `"exports"` entries. I'll push up a new build with the `"browser"` entrypoint to see if that helps.

**Comment by rbuckton** [comment]
Please try with `1.0.0-pre.39` and let me know if you're still getting this error.

**Comment by unicomp21** [comment]
still getting an error @rbuckton 

        "@esfx/collections": "^1.0.0-pre.39",
        "@esfx/equatable": "^1.0.0-pre.39",
        "@esfx/struct-type": "^1.0.0-pre.39",

ERROR in ./node_modules/@esfx/equatable/dist/esm/index.js 18:0-40
Module not found: Error: Can't resolve '#hashCode' in '/Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm'
resolve '#hashCode' in '/Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm'
  using description file: /Users/johndavis/repo/dev/babylonjs-webpack-es6/node_modules/@esfx/equatable/dist/esm/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
 @ ./src/voxels/point.ts 1:0-68 8:5-21 14:5-19 16:13-26 16:31-38 17:13-26 17:31-38 18:13-26 18:31-38
 @ ./src/voxels/voxels_cube.ts 3:0-33 20:15-33
 @ ./src/voxels/scratchpad.ts 1:0-44 11:27-38
 @ ./src/index.ts 15:0-49 52:42-63

webpack 5.74.0 compiled with 1 error in 15493 ms

**Comment by unicomp21** [comment]
@rbuckton here is the reference webpack setup i'm using for babylonjs, just npm i from it and repro should happen?

https://github.com/RaananW/babylonjs-webpack-es6

**Comment by rbuckton** [comment]
This looks like a bug in webpack/enhanced-resolve. It tries to look up `#hashCode` using the `ImportsFieldPlugin`, but the package.json it gives it is the package stub file, not the root package.json file.

**Comment by rbuckton** [comment]
It turns out this isn't a bug with webpack, but a side-effect of how I tried to support dual ESM/CJS emit. I'm going to have to roll back to only commonJS output for the time being. I should be able to do that tomorrow.

**Comment by unicomp21** [comment]
Does this mean ESM won't be supported?

https://github.com/wessberg/cjstoesm

**Comment by rbuckton** [comment]
Can you try with the `-pre.40` build I just published? It still includes esm outputs, I just changed the mechanism I use to generate them so that they have `.mjs` extensions so I no longer need the package.json stub that is getting in the way of `"imports"` map resolution.

**Comment by unicomp21** [comment]
@rbuckton got a new error now ...

        "@esfx/collections": "^1.0.0-pre.41",
        "@esfx/equatable": "^1.0.0-pre.41",
        "@esfx/struct-type": "^1.0.0-pre.41",

export 'HashSet' (imported as 'HashSet') was not found in '@esfx/collections' (module has no exports)
 @ ./src/voxels/scratchpad.ts 1:0-44 11:27-38
 @ ./src/index.ts 15:0-49 52:42-63

**Comment by rbuckton** [comment]
IF you could, give `1.0.0-pre.42` a try. I think I have these issues sorted out now.

**Comment by unicomp21** [comment]
@rbuckton lol, now I'm getting another error, but this one is at runtime.

Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    at putValueInView (startup:6:1)
    at PrimitiveTypeInfo.writeTo (startup:6:1)
    at StructFieldInfo.writeTo (startup:6:1)
    at Point3.set (startup:6:1)
    at Point3.copyFromVector3 (point.ts:30:15)
    at Point3.fromVector3 (point.ts:36:15)
    at voxels_cube.world_to_cube (voxels_cube.ts:22:16)
    at voxels_cube.set (voxels_cube.ts:25:28)
    at scratchpad.make_roads (scratchpad.ts:17:24)
    at index.ts:46:43

**Comment by rbuckton** [comment]
It is a never ending game of Whack-a-mole™. Do you have a repro I can try? Also, are you running in an environment that supports SAB? Some browsers disabled it for awhile due to speculative execution vulnerabilities.

**Comment by unicomp21** [comment]
@rbuckton try this branch -> hashcode

https://github.com/unicomp21/babylonjs-typescript-starter

**Comment by unicomp21** [comment]
I'm running the latest chrome on macos.

**Comment by rbuckton** [comment]
Yeah, it seems most vendors still have SAB disabled due to Specter/Meltdown. I have a few places where I check `x instanceof SharedArrayBuffer` that are failing due to it not being available, so I will add some checks to work around that.

**Comment by rbuckton** [comment]
`1.0.0-pre.43` should have a fix for that as soon as the publish workflow completes, probably in about 30 minutes.

**Comment by unicomp21** [comment]
@rbuckton that fixed it!  Call me grateful, many thanks for creating this amazing framework!

**Comment by rbuckton** [comment]
I should be dropping the prerelease tag shortly.
