### ISSUE TITLE
Can struct types support generics?

### ISSUE THREAD

**Issue by unicomp21** [esfx/esfx#77]

**Comment by rbuckton** [comment]
Not really. esfx structs require a fixed layout, so you can't really substitute other, differently shaped structs as values. You can use generics to constrain primitive values using something like an `enum`, but it's not easy to do in practice. I may tinker a bit to see if its possible to use instantiation expressions to introduce generics in this way:

![image](https://user-images.githubusercontent.com/3902892/213503608-eef4b52b-09da-441e-ab16-f4071a3e5eaa.png)


I may also look into a way to make the contents slightly more flexible in the future, not unlike a C-style `union`, but the union itself would still need to have a fixed size. Maybe something like this:

```ts
// `i` and `f` point to the same offset. `Data.SIZE` is 8
const Data = StructType([
  { union: [
    { name: "i", type: int32 },
    { name: "f", type: float64 },
  ] }
]);
```

**Comment by unicomp21** [comment]
Thanks!
